name: Security Headers

on:
  push:
    branches: [ main ]

jobs:
  security-headers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Add Security Headers
      run: |
        echo "Configurando headers de seguridad para GitHub Pages..."
        echo "Nota: GitHub Pages tiene limitaciones en headers personalizados"
        echo "Se recomienda usar Netlify o Vercel para headers completos" 